title: Reginald Erzoah
logo: /Images/profile.png
description: 
  <br><br>
  <a href="https://gh.linkedin.com/in/reginald-erzoah">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
